language: rust
rust:
  - nightly
os:
  - linux
  - osx
addons:
  artifacts: true
  debug: true
  paths:
  - target/release/libbureaucrat*

script: cargo build && cargo test && cargo build --release && mv target/release/libbureaucrat.* target/ && rm -rf target/release && rm -rf target/debug/
